{  
    "displayKey":[  
       "name",
       "originator_company",
       "drug_class"
    ],
    "iconsKey":[  
       "roa",
       "development_status"
    ],
    "colorsKey":[  
       "moa"
    ],
    "phases":{  
       "2017":{  
          "priority":0,
          "assets":[  
            {  
                "id":"128",
                "brand_name":"Olumiant",
                "generic_name":"baricitinib",
                "other_name":"INCB-028050",
                "name":"Olumiant",
                "originator_company":[  
                   "Incyte"
                ],
                "licensee_company":[  
                   "Eli+Lilly"
                ],
                "moa":[  
                   "JAK+1/2+inhibitor"
                ],
                "drug_class":"Small+Molecule",
                "developmentphase_comment":"",
                "other_comments":"<ul><li><p>Baricitinib+was+approved+in+the+EU+(Feb'17)+and+in+Japan+(Jul'17)+under+the+brand+name+\"Olumiant\".<br+/><br+/>Per+Eli+Lilly+2018+financial+guidance,+company+has+resubmitted+NDA+to+the+US+FDA+in+early+Dec’17.+Assuming+FDA+to+classify+refilled+application+as+a+Class+II+resubmission+(as+expected+by+Eli+Lilly),+six-month+is+considered+for+review+cycle.+FDA+approval+anticipated+in+June+2018.</p></li></ul>",
                "roa":[  
                   {  
                      "name":"Oral",
                      "iconPath":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/oral.png"
                   }
                ],
                "colors":{  
                   "JAK+1/2+inhibitor":"#6b2988"
                }
             }
          ],
          "color":{  
             "background":"#333333",
             "color":"#ffffff"
          }
       },
       "2019":{  
          "priority":1,
          "assets":[  
             {  
                "id":"142",
                "brand_name":"",
                "generic_name":"Upadacitinib",
                "other_name":"ABT+494",
                "name":"Upadacitinib",
                "originator_company":[  
                   "AbbVie"
                ],
                "licensee_company":[  
 
                ],
                "moa":[  
                   "JAK+1+inhibitor"
                ],
                "drug_class":"Small+Molecule",
                "developmentphase_comment":"",
                "other_comments":"<ul><li><p>In+2017,+AbbVie+reported+positive+results+from+three+Phase+III+studies+for+upadacitinib+in+RA.+AbbVie+expects+the+data+from+two+additional+pivotal+trials+in+the+RA+program+in+H1+2018+and+regulatory+submission+in+H2+2018,+with+commercialization+expected+in+2019.</p></li><li><p>At+ACR+2017,+AbbVie+presented+positive+results+from+SELECT+NEXT+and+SELECT+BEYOND+study.</p></li></ul>",
                "roa":[  
                   {  
                      "name":"Oral",
                      "iconPath":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/oral.png"
                   }
                ],
                "colors":{  
                   "JAK+1+inhibitor":"#5f5039"
                }
             },
             {  
                "id":"285",
                "brand_name":"",
                "generic_name":"Peficitinib",
                "other_name":"ASP015K",
                "name":"Peficitinib",
                "originator_company":[  
                   "Astellas"
                ],
                "licensee_company":[  
 
                ],
                "moa":[  
                   "JAK+inhibitor"
                ],
                "drug_class":"Small+Molecule",
                "developmentphase_comment":"",
                "other_comments":"<ul><li><p>Peficitinib+is+currently+in+Phase+3+clinical+stage+in+Asia,+including+Japan+and+in+Phase+2+in+the+US+and+EU.<br+/><br+/>In+Feb'18,+Astellas+Pharma+announced+positive+results+from+two+Phase+3+trials+in+RA+patients+with+an+inadequate+response+to+existing+therapy.+Based+on+the+results+of+these+trials,+Astellas+intends+to+discuss+the+data+with+the+regulatory+authorities+in+Japan+and+other+Asian+countries+to+support+filing+in+Q1+2018.</p></li></ul>",
                "roa":[  
                   {  
                      "name":"Oral",
                      "iconPath":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/oral.png"
                   }
                ],
                "colors":{  
                   "JAK+inhibitor":"#0818ee"
                }
             }
          ],
          "color":{  
             "background":"#333333",
             "color":"#ffffff"
          }
       },
       "2020":{  
          "priority":2,
          "assets":[  
             {  
                "id":"141",
                "brand_name":"",
                "generic_name":"Filgotinib",
                "other_name":"GLPG-0634,+GS-6034",
                "name":"Filgotinib",
                "originator_company":[  
                   "Galapagos+"
                ],
                "licensee_company":[  
                   "Gilead+Sciences+"
                ],
                "moa":[  
                   "JAK+1+inhibitor"
                ],
                "drug_class":"Small+Molecule",
                "developmentphase_comment":"",
                "other_comments":"<ul><li><p>Galapagos+and+Gilead+Sciences+have+launched+pivotal+FINCH+Phase+III+program+(NCT02889796,+NCT02873936+and+NCT02886728)+investigating+the+efficacy+and+safety+of+filgotinib+(100+mg+and+200+mg)+once+daily+in+RA.+Global+program+is+designed+to+include+broad+population+of+patients+with+active+RA,+ranging+from+early+stage+to+biologic-experienced+patients.+The+estimated+completion+of+Phase+III+trial+is+April+2019.</p></li><li><p>In+Dec'17,+Galapagos+announced+the+decision+to+opt-in+on+the+co-promotion+of+filgotinib+with+collaboration+partner+Gilead+Sciences+in+eight+European+countries.<br+/><br+/>In+Dec'15,+Galapagos+and+Gilead+Sciences+entered+into+a+global+partnership+for+the+development+and+commercialization+of+filgotinib+for+inflammatory+indications.</p></li></ul>",
                "roa":[  
                   {  
                      "name":"Oral",
                      "iconPath":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/oral.png"
                   }
                ],
                "colors":{  
                   "JAK+1+inhibitor":"#5f5039"
                }
             }
          ],
          "color":{  
             "background":"#333333",
             "color":"#ffffff"
          }
       },
       "2021":{  
          "priority":3,
          "assets":[  
             {  
                "id":"140",
                "brand_name":"",
                "generic_name":"Olokizumab",
                "other_name":"CDP-6038",
                "name":"Olokizumab",
                "originator_company":[  
                   "UCB+Pharma"
                ],
                "licensee_company":[  
                   "R-Pharm"
                ],
                "moa":[  
                   "IL-6+inhibitor"
                ],
                "drug_class":"mAb",
                "developmentphase_comment":"",
                "other_comments":"<ul><li><p>R-Pharm+is+developing+olokizumab+(IL-6+inhibitor)+for+the+treatment+of+RA.+R-Pharm+is+conducting+four+Phase+III+studies+in+moderate+to+severe+RA+patients+(NCT02760433,+NCT02760368,+NCT03120949+and+NCT02760407).+Phase+3+completion+expected+in+December+2019.<br+/><br+/>In+2013,+UCB+granted+a+WW+exclusive+license+to+R-Pharm,+to+develop+and+commercialize+olokizumab+in+all+indications,+including+RA.</p></li></ul>",
                "roa":[  
                   {  
                      "name":"SC",
                      "iconPath":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/sc.png"
                   }
                ],
                "colors":{  
                   "IL-6+inhibitor":"#6200d3"
                }
             }
          ],
          "color":{  
             "background":"#333333",
             "color":"#ffffff"
          }
       }
    },
    "legends":{  
       "colors":{  
          "JAK+1/2+inhibitor":"#6b2988",
          "JAK+1+inhibitor":"#5f5039",
          "JAK+inhibitor":"#0818ee",
          "IL-6+inhibitor":"#6200d3"
       },
       "icons":{  
          "Oral":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/oral.png",
          "SC":"genzyme-staging.integratedge.com/assets/624aaeec/images/genzyme/sc.png"
       }
    },
    "subfilters":{  
       "269":"IL-6+inhibitor",
       "272":"JAK+1+inhibitor",
       "273":"JAK+1/2+inhibitor",
       "275":"JAK+inhibitor"
    }
 }